default: &default
    adapter: postgresql
    encoding: unicode
    host: <%= ENV['DB_HOST'] || "localhost" %>
    port: <%= ENV['DB_PORT'] || 5432 %>
    username: <%= ENV['DB_USER'] %>
    password: <%= ENV['DB_PASS'] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
    <<: *default
    database: dbftk1brcu5ttd
    username: kazdushjzwrtjy
    password: 9bf391a57249486011bb45cae75656aecf2831044c11ebb036cddd7315d9b932
    timeout: 5000
test:
    <<: *default
    database: <%= ENV['DB_NAME'] %>_test

staging:
    adapter: postgresql
    database: <%= ENV['DB_NAME'] %>
    host: <%= ENV['DB_HOST'] %>
    username: <%= ENV['DB_USER'] %>
    password: <%= ENV['DB_PASS'] %>
    timeout: 5000